### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by kuohao233** [wenzhu23333/Differential-Privacy-Based-Federated-Learning#11]
想问一下大佬有没有试过用Opacus直接进行差分隐私的添加，我这边用Opacus不同的差分预算的准确率却差不多，很奇怪

**Comment by wenzhu23333** [comment]
理论上准确率应该会差别很大，有没有试过隐私预算调整范围大一些？

**Comment by kuohao233** [comment]
> 理论上准确率应该会差别很大，有没有试过隐私预算调整范围大一些？

一般是调几个范围呢，感觉Opacus的隐私预算数值好像放得比较宽松一点的样子

**Comment by wenzhu23333** [comment]
> > 理论上准确率应该会差别很大，有没有试过隐私预算调整范围大一些？
> 
> 一般是调几个范围呢，感觉Opacus的隐私预算数值好像放得比较宽松一点的样子

这个与你的query次数有关系，如果次数比较多，隐私预算相应要大一些，不然utility会受到很大影响。一般来说我的调参经验是确定一个小的隐私预算和一个能接受的大的隐私预算，然后在这个范围之中调出一个合理的效果。如果涉及到其他参数例如cliping bound的话，那么就先需要调到一个最优的cliping，然后再调隐私预算。
