### ISSUE TITLE
你好，关于本地训练回合问题

### ISSUE THREAD

**Issue by a-row-person** [wenzhu23333/Differential-Privacy-Based-Federated-Learning#12]
您好，我想要更改本地训练回合，这样需要怎么改，会出现什么问题？我修改本地训练回合是为了和我之前做的实验保持实验环境一致。

**Comment by wenzhu23333** [comment]
如果修改本地训练回合，需要重新计算敏感度，并根据敏感度计算的过程决定是否还需要per sample clip的操作，如果不需要，根据敏感度和隐私预算添加噪声即可，可以移除opacus部分的代码。

**Comment by a-row-person** [comment]
好的，感谢作者大大
