### ISSUE TITLE
Hyperparameters for training cnn for cifar 10

### ISSUE THREAD

**Issue by Toby-Kang** [wenzhu23333/Differential-Privacy-Based-Federated-Learning#13]
Hi Wenzhu! I wonder if you can help to share the hyperparameters you used when training the CNN model for cifar10 dataset. For me the best test accuracy that I can achieve when there is no dp is around 34%. Is it the similar story on your side as well? Many thanks!

**Comment by wenzhu23333** [comment]
The following are the hyperparameters and results I once trained: 
For dp-sgd：
dp_clip=1e-5, frac=1, sampling rate=0.1, client num=50, lr=0.2, lr_decay=0.999, 2000 rounds
no_dp: 69%
epsilon=350: 52%
epsilon=51%
