### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Speed-Fiorna** [wenzhu23333/Differential-Privacy-Based-Federated-Learning#15]
您好，想问一下几个问题
1.每一层能否使用不同的隐私预算进行加噪，如果用这种方式，那么总隐私消耗应该怎样计算呢
2.使用f-DP进行隐私预算的计算方法，是与RDP转(ε,δ)-DP的方法类似的嘛

**Comment by wenzhu23333** [comment]
1、参考：Adaptive Laplace Mechanism: Differential Privacy Preservation in Deep Learning NhatHai Phan, Xintao Wu, Han Hu, Dejing Dou. IEEE ICDM'17, New Orleans, USA 18-21 November 2017. https://arxiv.org/abs/1709.05750.
2、f-dp似乎没有epsilon的概念，具体转换还需参考原文。

**Comment by Speed-Fiorna** [comment]
谢谢大佬指教
