### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by beiyuouo** [wenzhu23333/Differential-Privacy-Based-Federated-Learning#2]
Thanks for your good work!

Maybe this should be equal to `Laplace` ?

https://github.com/wenzhu23333/Differential-Privacy-Based-Federated-Learning/blob/790bd56b4357a4e2d53b33fb092e5147b1eebb18/models/Update.py#L69

**Comment by wenzhu23333** [comment]
Thanks for your comment, I have fixed this.
