### ISSUE TITLE
关于梯度加噪的问题

### ISSUE THREAD

**Issue by sherlock-CHN** [wenzhu23333/Differential-Privacy-Based-Federated-Learning#22]
作者你好，看到您和另一个人在讨论加噪的问题。我这里有几点疑问，我也是刚开始学DP+FL不久，希望能得到您的解答。
看到您说这份代码是对梯度进行加噪。我问了下GPT，他说state_dict是模型的参数，并不是梯度，提的是模型的参数。

![111](https://github.com/wenzhu23333/Differential-Privacy-Based-Federated-Learning/assets/54991793/33706b10-33cf-48e9-8937-9dbee0eb9aa3)

![image](https://github.com/wenzhu23333/Differential-Privacy-Based-Federated-Learning/assets/54991793/8956ddc6-4611-48f6-90e7-ae1f12e4686d)
如果是对梯度加噪的话，我看某些论文需要在加噪后还需要除以批量样本数，但我在您的代码里并没有找到这个操作，是我哪里理解错了吗？
![1233](https://github.com/wenzhu23333/Differential-Privacy-Based-Federated-Learning/assets/54991793/6b5b0920-c34e-4b5a-bd54-a48b95670f0d)

**Comment by wenzhu23333** [comment]
1、本仓库的实现使用的是full batch size，也就是说batch size大小为数据集大小。
2、将1/L分之一乘进去，可以此项也可以反映在噪声的Sensitivity中，本仓库是在sensitivity中除去了batch size的大小（也即是数据集大小）。
