### ISSUE TITLE
精度很低

### ISSUE THREAD

**Issue by zz978233034** [wenzhu23333/Differential-Privacy-Based-Federated-Learning#3]
你好，我想请问，为什么我在运行这个代码的时候，我发现他不收敛是咋回事呢，精度一直在十几

**Comment by AshliaYan** [comment]
我也有同样的问题，请问你解决了吗？

**Comment by zz978233034** [comment]
没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月17日(星期四) 晚上9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenzhu23333/Differential-Privacy-Based-Federated-Learning] 精度很低 (Issue #3)





 
我也有同样的问题，请问你解决了吗？

**Comment by dDCTRr** [comment]
我也遇到了这个问题，这个project有没有讨论群什么的呀

**Comment by wenzhu23333** [comment]
仓库已更新，添加了Per Sample Gradient Clip，以及run.sh里面提供了一些example，结果见readme。
